apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-frontend-to-backend
  labels:
    app: uptime-monitor-backend
spec:
  podSelector:
    matchLabels:
      app: uptime-monitor-backend
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: uptime-monitor-frontend
    ports:
    - protocol: TCP
      port: 8000
