FROM nginx:alpine

LABEL maintainer="Somay Khatri <khatrisomay@github>"
LABEL description="Uptime Monitor Ingress Nginx Reverse Proxy Gateway"

COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 \
  CMD wget --quiet --tries=1 --spider http://localhost:80/ || exit 1

CMD ["nginx", "-g", "daemon off;"]
