FROM jenkins/inbound-agent:alpine-jdk17

USER root

# Install Docker CLI, Curl, Git, Node.js, Python3, and Pip
RUN apk add --no-cache \
    docker-cli \
    curl \
    git \
    nodejs \
    npm \
    python3 \
    py3-pip \
    bash

# Install kubectl
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
    chmod +x kubectl && \
    mv kubectl /usr/local/bin/

# Install Helm
RUN curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

USER jenkins
